version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
      - DB_DIALECT=postgres
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - UI_ORIGIN=http://localhost:4200/
      - INFURA_ID=8fcacee838e04f31b6ec145eb98879c8
      - SECRET_COOKIE_PASSWORD=dyTtTgMg6pkzzNxqGMXpPqmXV6W9WahF
      - COOKIE_NAME='iron-session/siwe-app-gnosis'
    depends_on:
      - db
      - cache
      - jaeger
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache-data:/var/lib/redis
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - '4318:4318'
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - jaeger-data:/var/lib/jaeger
volumes:
  db:
    driver: local
  cache-data:
    driver: local
  jaeger-data:
    driver: local
